# Generated by Django 6.0.1 on 2026-02-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_studentreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreport',
            old_name='student',
            new_name='reg_no',
        ),
    ]
