# Generated by Django 6.0.1 on 2026-02-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_formmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
